name: Compile JSON to Binary Rule-Set

on:
  schedule:
  # 每周1早上4点运行一次
    - cron: '0 20 * * 0'
  workflow_dispatch:

jobs:
  generate-and-compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: pip install requests

    - name: Generate TENCENT IP CIDR Data
      run: |
        python -c '
        import requests
        import json
        import os

        url = "https://ipinfo.io/widget/demo/AS132203"
        response = requests.get(url)

        if response.status_code == 200:
            json_data = response.json()
            cidr_list = [prefix["netblock"] for prefix in json_data.get("prefixes", [])]

            output = {
                "version": 1,
                "rules": [
                    {
                        "ip_cidr": cidr_list
                    }
                ]
            }

            with open("tencent.json", "w", encoding="utf-8") as f:
                json.dump(output, f, indent=4, ensure_ascii=False)
            
            print("Content of tencent.json:")
            with open("tencent.json", "r", encoding="utf-8") as f:
                print(f.read())

            print("\nFiles in current directory:")
            print(os.listdir("."))
        else:
            print(f"Error: Unable to fetch data (HTTP {response.status_code})")
        '

    - name: Download and extract sing-box
      run: |
        wget https://github.com/SagerNet/sing-box/releases/download/v1.9.3/sing-box-1.9.3-linux-amd64.tar.gz
        tar -xzvf sing-box-1.9.3-linux-amd64.tar.gz

    - name: Compile JSON files to binary rule-set
      run: |
        for file in *.json; do
          echo "Processing file: $file"
          cat "$file"
          ./sing-box-1.9.3-linux-amd64/sing-box rule-set compile --output "${file%.json}.srs" "$file"
        done

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add tencent.json *.srs
        git commit -m "Update TENCENT IP CIDR Data and compile to SRS" || echo "No changes to commit"
        git push || echo "No changes to push"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
