name: Compile JSON to Binary Rule-Set

on:
  push:
    branches:
      - main

jobs:
  generate-and-compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: pip install requests
      
    - name: Download and extract sing-box
      run: |
        wget https://github.com/SagerNet/sing-box/releases/download/v1.9.3/sing-box-1.9.3-linux-amd64.tar.gz
        tar -xzvf sing-box-1.9.3-linux-amd64.tar.gz

    - name: Compile JSON files to binary rule-set
      run: |
        for file in *.json; do
          ./sing-box-1.9.3-linux-amd64/sing-box rule-set compile --output "${file%.json}.srs" "$file"
        done

    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add *.srs
        git add *.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Compile JSON to binary rule-set" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
